DROP TABLE IF EXISTS COFFEE_DESCRIPTION;
DROP TABLE IF EXISTS COFFEE_HOUSE;
DROP TABLE IF EXISTS MERCH_INVENTORY;
DROP TABLE IF EXISTS COFFEE_INVENTORY;
DROP TABLE IF EXISTS RSS_FEED;
DROP TABLE IF EXISTS COFFEE;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS DATA_REPOSITORY;
